'use client'
import './globals.css'
import { Inter } from 'next/font/google'

import NavBar from '@/components/NavBar'
import Footer from '@/components/Footer'
import { usePathname } from "next/navigation";

import Providers from '@/redux/provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const path = usePathname()


  return (
    <html lang="en">
      <Providers>
      <body className={inter.className}>
        {
          !path.includes('login') &&
          !path.includes('admin') &&
          !path.includes('register') && <NavBar/>
        }
        {children}

        {
          !path.includes('login') &&
          !path.includes('admin') &&
          !path.includes('register') && <Footer/>
        }
        
        </body>
      </Providers>
    </html>
  )
}
